# Generated by Django 5.2.12 on 2026-04-07 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=32)),
                (
                    "exchange",
                    models.CharField(
                        choices=[
                            ("binance", "Binance"),
                            ("alpaca", "Alpaca"),
                            ("manual", "Manual / CSV Import"),
                        ],
                        db_index=True,
                        default="binance",
                        max_length=16,
                    ),
                ),
                (
                    "timeframe",
                    models.CharField(
                        choices=[
                            ("1m", "1 Minute"),
                            ("5m", "5 Minutes"),
                            ("15m", "15 Minutes"),
                            ("30m", "30 Minutes"),
                            ("1h", "1 Hour"),
                            ("4h", "4 Hours"),
                            ("1d", "1 Day"),
                            ("1w", "1 Week"),
                        ],
                        db_index=True,
                        default="1m",
                        max_length=4,
                    ),
                ),
                ("time", models.DateTimeField(db_index=True)),
                ("open", models.DecimalField(decimal_places=8, max_digits=20)),
                ("high", models.DecimalField(decimal_places=8, max_digits=20)),
                ("low", models.DecimalField(decimal_places=8, max_digits=20)),
                ("close", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "volume",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                ("extra", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["time"],
                "indexes": [
                    models.Index(
                        fields=["symbol", "timeframe", "time"],
                        name="data_market_symbol_78dd30_idx",
                    )
                ],
                "unique_together": {("symbol", "exchange", "timeframe", "time")},
            },
        ),
        migrations.CreateModel(
            name="StrategyRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("strategy_name", models.CharField(db_index=True, max_length=64)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("backtest", "Backtest"),
                            ("paper", "Paper Trading"),
                            ("live", "Live Trading"),
                        ],
                        max_length=16,
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=32)),
                (
                    "exchange",
                    models.CharField(
                        choices=[
                            ("binance", "Binance"),
                            ("alpaca", "Alpaca"),
                            ("manual", "Manual / CSV Import"),
                        ],
                        default="binance",
                        max_length=16,
                    ),
                ),
                (
                    "timeframe",
                    models.CharField(
                        choices=[
                            ("1m", "1 Minute"),
                            ("5m", "5 Minutes"),
                            ("15m", "15 Minutes"),
                            ("30m", "30 Minutes"),
                            ("1h", "1 Hour"),
                            ("4h", "4 Hours"),
                            ("1d", "1 Day"),
                            ("1w", "1 Week"),
                        ],
                        default="1m",
                        max_length=4,
                    ),
                ),
                ("config", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "initial_balance",
                    models.DecimalField(decimal_places=8, default=10000, max_digits=20),
                ),
                (
                    "final_balance",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                ("metrics", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="strategy_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="TradeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=32)),
                (
                    "exchange",
                    models.CharField(
                        choices=[
                            ("binance", "Binance"),
                            ("alpaca", "Alpaca"),
                            ("manual", "Manual / CSV Import"),
                        ],
                        default="binance",
                        max_length=16,
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("LONG", "Long"), ("SHORT", "Short")], max_length=8
                    ),
                ),
                ("entry_price", models.DecimalField(decimal_places=8, max_digits=20)),
                ("exit_price", models.DecimalField(decimal_places=8, max_digits=20)),
                ("quantity", models.DecimalField(decimal_places=8, max_digits=20)),
                ("pnl", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "commission",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "slippage",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                ("opened_at", models.DateTimeField()),
                ("closed_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to="data.strategyrun",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-closed_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "binance_api_key",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                (
                    "binance_api_secret",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                (
                    "alpaca_api_key",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                (
                    "alpaca_api_secret",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                (
                    "default_balance",
                    models.DecimalField(decimal_places=2, default=10000, max_digits=20),
                ),
                (
                    "risk_tolerance",
                    models.CharField(
                        choices=[
                            ("conservative", "Conservative"),
                            ("moderate", "Moderate"),
                            ("aggressive", "Aggressive"),
                        ],
                        default="moderate",
                        max_length=16,
                    ),
                ),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EquityCurve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("balance", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "unrealised_pnl",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                ("total_equity", models.DecimalField(decimal_places=8, max_digits=20)),
                ("drawdown", models.FloatField(default=0.0)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equity_curve",
                        to="data.strategyrun",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
                "indexes": [
                    models.Index(
                        fields=["run", "timestamp"],
                        name="data_equity_run_id_b28225_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StrategySignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                (
                    "action",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell"), ("HOLD", "Hold")],
                        max_length=8,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=8, max_digits=20)),
                ("confidence", models.FloatField(blank=True, null=True)),
                (
                    "stop_loss",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                (
                    "take_profit",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signals",
                        to="data.strategyrun",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
                "indexes": [
                    models.Index(
                        fields=["run", "timestamp"],
                        name="data_strate_run_id_8bc2e1_idx",
                    )
                ],
            },
        ),
    ]
