# Generated by Django 5.2.12 on 2026-04-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0002_timescaledb_hypertables"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookTickerSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=32)),
                (
                    "exchange",
                    models.CharField(
                        choices=[
                            ("binance", "Binance"),
                            ("alpaca", "Alpaca"),
                            ("manual", "Manual / CSV Import"),
                        ],
                        default="binance",
                        max_length=16,
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                (
                    "best_bid_price",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "best_bid_qty",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "best_ask_price",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "best_ask_qty",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "spread",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["symbol", "timestamp"],
                        name="data_bookti_symbol_487fc5_idx",
                    ),
                    models.Index(
                        fields=["symbol", "exchange", "timestamp"],
                        name="data_bookti_symbol_2ac686_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OrderBookSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=32)),
                (
                    "exchange",
                    models.CharField(
                        choices=[
                            ("binance", "Binance"),
                            ("alpaca", "Alpaca"),
                            ("manual", "Manual / CSV Import"),
                        ],
                        default="binance",
                        max_length=16,
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("bids", models.JSONField(default=list)),
                ("asks", models.JSONField(default=list)),
                (
                    "best_bid_price",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "best_bid_qty",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "best_ask_price",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "best_ask_qty",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "spread",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                ("spread_pct", models.FloatField(default=0)),
                (
                    "mid_price",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "total_bid_qty",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "total_ask_qty",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                ("book_imbalance", models.FloatField(default=0)),
                ("last_update_id", models.BigIntegerField(default=0)),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["symbol", "timestamp"],
                        name="data_orderb_symbol_8ded47_idx",
                    ),
                    models.Index(
                        fields=["symbol", "exchange", "timestamp"],
                        name="data_orderb_symbol_196e95_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TickerSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=32)),
                (
                    "exchange",
                    models.CharField(
                        choices=[
                            ("binance", "Binance"),
                            ("alpaca", "Alpaca"),
                            ("manual", "Manual / CSV Import"),
                        ],
                        default="binance",
                        max_length=16,
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                (
                    "price_change",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                ("price_change_pct", models.FloatField(default=0)),
                (
                    "weighted_avg_price",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "prev_close",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "last_price",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "volume",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "quote_volume",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "open_price",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "high_price",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "low_price",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                ("trade_count", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["symbol", "timestamp"],
                        name="data_ticker_symbol_324941_idx",
                    ),
                    models.Index(
                        fields=["symbol", "exchange", "timestamp"],
                        name="data_ticker_symbol_09ddd0_idx",
                    ),
                ],
            },
        ),
    ]
